<?xml version="1.0" encoding="utf-8"?><Database Name="Cert" Class="CertDataBaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=Cert;User ID=sa" SettingsObjectName="SignCert.Properties.Settings" SettingsPropertyName="CertConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PdfBuildTask" Member="PdfBuildTask">
    <Type Name="PdfBuildTask">
      <Column Name="BuildTaskId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContractId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HasFinishGeneralPdf" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ContractType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserCert" Member="UserCert">
    <Type Name="UserCert">
      <Column Name="UserCertId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PublicKeyPath" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="PrivateKeyPath" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Avaible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CertSerialNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserCertOverview" Member="UserCertOverview">
    <Type Name="UserCertOverview">
      <Column Name="UserCertOverViewId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AgreeAutoSign" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SignedNumber" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AgreeAutoSignTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>